version: '3.7'

services:
  postgres:
    image: postgres:12
    networks:
      - network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./config/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
        - '6379:6379'
    environment:
      REDIS_PASSWORD: 'pass123'


networks:
  network:
    driver: bridge