version: '3'

services:
  postgres:
    image: postgres:12
    networks:
      - network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

migrate:
        image: migrate/migrate
        networks:
            - network
        volumes:
            - .:/migrations
        command: ["-path", "/config/migrations", "-database",  "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable", "up", "3"]
        links: 
            - d
networks:
  network:
    driver: bridge