version: '3.7'

services:
  postgres:
    image: postgres:12
    networks:
      - network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
  migrator:
    networks:
      - network
    build:
      dockerfile: Dockerfile.migrator
      context: .
    healthcheck:
      test: [ "CMD", "/usr/local/bin/goose", "status" ]
      retries: 3
      interval: 5s
    restart: on-failure
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://postgres:postgres@postgres:5432/postgres
    command:
      - up
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
        - '6379:6379'
    environment:
      REDIS_PASSWORD: 'pass123'

volumes:
  pg_data:

networks:
  network:
    driver: bridge